---
- name: Create facts directory
  file: path='/etc/ansible/facts.d'
        state='directory'

- name: Install Java
  yum: name=java-1.8.0-openjdk-devel
       state=present

- name: Set the Spark node addresses
  set_fact: 
    spark_addresses: "spark://{% for host in groups['masters'] %}{{ host }}:{{ spark_worker_port }}{% if not loop.last %},{% endif %}{% endfor %}"